name: Sync Repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "iliasmachairas@outlook.com"
          git config --global user.name "iliasmachairas"
          git config --global credential.helper store

      - name: Clone destination repository
        run: |
          echo "https://${{ secrets.PAT }}@github.com" > ~/.git-credentials
          git clone https://${{ secrets.PAT }}@github.com/iliasmachairas/sync_project.git
          cd sync_project
          git remote add source https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          git fetch source
          git checkout -b temp-branch source/main
          
          git rm -f .github/workflows/workflow.yml || true
          git commit -m "Remove workflow file from sync"

          git checkout main

          # Merge temp-branch into main, with strategy to favor changes from temp-branch
          git merge temp-branch -X theirs --allow-unrelated-histories

          # Handle merge conflicts
          git checkout --ours .github/workflows/workflow.yml  # keep changes from main branch
          git add .github/workflows/workflow.yml
          git merge --continue

          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          ORG_NAME: iliasmachairas
